/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in full projects. It is checked in here so
// the initial TypeScript skeleton can type-check before the first dev run.
